import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { parseDocument } from '../src/model.js'
import { ocdToDocument } from '../src/ocd.js'
import { buildReport, edgeSentence, inline, phrase, plural } from '../src/report.js'

const read = (path) => JSON.parse(readFileSync(new URL(path, import.meta.url), 'utf8'))
const date = new Date('2026-09-23T12:00:00Z')

function ctxFor(doc) {
  const byId = new Map(doc.nodes.map((n) => [n.id, n]))
  return { edgeTypes: doc.edgeTypes ?? {}, name: (id) => byId.get(id)?.label ?? id }
}

const pair = {
  nodes: [{ id: 'a', label: 'Alpha' }, { id: 'b', label: 'Beta' }],
}

describe('phrase', () => {
  it('classifies edge labels by how they read between two names', () => {
    expect(phrase('uses')).toBe('verb')
    expect(phrase('depends on')).toBe('verb')
    expect(phrase('draws graphs with')).toBe('verb')
    expect(phrase('pushes rules as MISP events')).toBe('action')
    expect(phrase('member of')).toBe('state')
    expect(phrase('affiliated with')).toBe('state')
    expect(phrase('API')).toBe('noun')
    expect(phrase('upstream')).toBe('noun')
    expect(phrase('')).toBe('none')
    expect(phrase('manages or co-manages')).toBe('verb')
    expect(phrase('reads and writes')).toBe('verb')
    expect(phrase('uses and pushes events')).toBe('action')
  })
})

describe('edgeSentence', () => {
  const sentence = (edge, edgeTypes) => edgeSentence(ctxFor({ ...pair, edgeTypes }), { from: 'a', to: 'b', ...edge })

  it('reads the arrow direction', () => {
    expect(sentence({ label: 'uses' })).toBe('**Alpha** uses **Beta**.')
    expect(sentence({ label: 'uses', direction: 'backward' })).toBe('**Beta** uses **Alpha**.')
    expect(sentence({ label: 'syncs with', direction: 'both' })).toBe('**Alpha** syncs with **Beta**, in both directions.')
  })

  it('keeps labels grammatical', () => {
    expect(sentence({ label: 'member of' })).toBe('**Alpha** is member of **Beta**.')
    expect(sentence({ label: 'pushes events' })).toBe('**Alpha** pushes events (→ **Beta**).')
    expect(sentence({ label: 'API' })).toBe('**Alpha** is linked to **Beta** (API).')
    expect(sentence({})).toBe('**Alpha** is linked to **Beta**.')
    expect(sentence({ label: 'federates with (sync)', to: 'a' })).toBe('**Alpha** federates with itself (sync).')
  })

  it('falls back on the edge type', () => {
    expect(sentence({ type: 'dep' }, { dep: { label: 'depends on', direction: 'backward' } })).toBe('**Beta** depends on **Alpha**.')
    expect(sentence({ type: 'contributes_to' })).toBe('**Alpha** contributes to **Beta**.')
  })
})

describe('buildReport', () => {
  it('describes every field of the example', () => {
    const doc = parseDocument(read('../examples/rulezet.json')).doc
    const md = buildReport(doc, { date, image: 'graph.png' })
    expect(md).toMatch(/^# Projects linked to Rulezet\n\n!\[Graph of Projects linked to Rulezet\]\[graph-image\]/)
    expect(md).toMatch(/\[graph-image\]: graph\.png\n$/)
    expect(md).toContain('This graph has 10 nodes (10 projects) connected by 12 relationships.')
    for (const node of doc.nodes) expect(md).toContain(`#### ${inline(node.label)}`)
    expect(md).toContain('- **Website:** <https://rulezet.org>')
    expect(md).toContain('**Rulezet** pushes rules as MISP events (→ **MISP**).')
    expect(md).toContain('- **Protocol:** REST via PyMISP (API key)')
    expect(md).toContain('## Tags')
    expect(md).toContain('*Report generated by Pivograph on 23 September 2026')
  })

  it('is deterministic', () => {
    const doc = parseDocument(read('../examples/rulezet.json')).doc
    expect(buildReport(doc, { date })).toBe(buildReport(doc, { date }))
  })

  it('merges sentences that differ only by their object (OCD hub)', () => {
    const doc = parseDocument(ocdToDocument(read('./fixtures/ocd-flowintel.json'))).doc
    const md = buildReport(doc, { date })
    const hub = md.split('\n').filter((l) => /^- \*\*.+\*\* maintains /.test(l))
    expect(hub.length).toBeGreaterThan(0)
    expect(hub[0]).toMatch(/, .* and /)
  })

  it('handles an empty graph and escapes Markdown in the data', () => {
    expect(buildReport({ meta: {}, nodes: [], edges: [] }, { date })).toContain('This graph is empty.')
    const md = buildReport({ meta: { title: 'A *b* [c]' }, nodes: [{ id: 'x', label: '<script>' }], edges: [] }, { date })
    expect(md).toContain('# A \\*b\\* \\[c\\]')
    expect(md).toContain('\\<script\\>')
    expect(md).not.toContain('<script>')
  })

  it('keeps inner capitals when lowering a type name', async () => {
    const { lowerFirst } = await import('../src/report.js')
    expect(lowerFirst('Open data')).toBe('open data')
    expect(lowerFirst('GitHub organisation')).toBe('GitHub organisation')
    expect(lowerFirst('MISP instance')).toBe('MISP instance')
  })

  it('pluralizes type names', () => {
    expect(plural(2, 'Library')).toBe('Libraries')
    expect(plural(2, 'Process')).toBe('Processes')
    expect(plural(1, 'Project')).toBe('Project')
  })
})
